#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Package a Basic Pitch SavedModel (stock or fine-tuned) for every runtime and,
# optionally, publish it as GitHub release assets (weights never go into git).
#
#   tools/model-export/export-model.sh <savedmodel_dir> <tag> [metrics.json] [--publish] [--latest]
#
# Writes build/model-export/<tag>/:
#   basic-pitch-<tag>-savedmodel.zip     TF SavedModel (dir "nmp/")
#   basic-pitch-<tag>-tfjs.zip           TF.js graph model (model.json + group1-shard1of1.bin)
#   basic-pitch-<tag>-coreml.zip         BasicPitchPoly.mlpackage (mlprogram, fp32, iOS16+), converted
#                                        with coremltools on Linux or macOS
#   SHA256SUMS, models.lock.snippet, NOTES.md
# --publish: gh release create/upload <tag>; --latest: also refresh the "model-latest" release.
#
# Environments (see docs/finetune/IOS_MODEL_HANDOFF.md):
#   TFJS_PY    python with tensorflowjs 4.22 + TF 2.15 (default /workspace/bp-ft/.venv-tfjs/bin/python)
#   COREML_PY  python with coremltools 8.3 + TF 2.15  (default /workspace/bp-ft/.venv-coreml/bin/python)
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SM="$(cd "$1" && pwd)"; TAG="$2"; METRICS="${3:-}"
PUBLISH=0; LATEST=0
for a in "$@"; do case "$a" in --publish) PUBLISH=1 ;; --latest) LATEST=1 ;; esac; done
case "$METRICS" in --*) METRICS="" ;; esac
TFJS_PY="${TFJS_PY:-/workspace/bp-ft/.venv-tfjs/bin/python}"
COREML_PY="${COREML_PY:-/workspace/bp-ft/.venv-coreml/bin/python}"
OUT="$ROOT/build/model-export/$TAG"
rm -rf "$OUT" && mkdir -p "$OUT/tmp"
P="basic-pitch-$TAG"

# SavedModel
cp -R "$SM" "$OUT/tmp/nmp"
(cd "$OUT/tmp" && zip -qrX "$OUT/$P-savedmodel.zip" nmp)

# TF.js (same converter flags as the web demo's stock model)
"$TFJS_PY" - "$SM" "$OUT/tmp/tfjs" <<'PY'
import sys
from tensorflowjs.converters import tf_saved_model_conversion_v2 as c
c.convert_tf_saved_model(sys.argv[1], sys.argv[2], signature_def="serving_default",
                         saved_model_tags="serve", strip_debug_ops=True)
PY
(cd "$OUT/tmp/tfjs" && zip -qrX "$OUT/$P-tfjs.zip" model.json group1-shard*)

# Core ML (fixed input shape, same names as the stock nmp.mlpackage)
"$COREML_PY" - "$SM" "$OUT/tmp/BasicPitchPoly.mlpackage" <<'PY' 2>&1 | grep -v "passes/s\|ops/s" || true
import sys
import coremltools as ct
import tensorflow as tf
m = tf.keras.models.load_model(sys.argv[1], compile=False)
in_name = m.inputs[0].name.split(":")[0]  # stock: input_2; models.model() rebuilds: input_1
ml = ct.convert(m, convert_to="mlprogram", source="tensorflow",
                inputs=[ct.TensorType(name=in_name, shape=(1, 43844, 1))],
                compute_precision=ct.precision.FLOAT32,
                minimum_deployment_target=ct.target.iOS16)
spec = ml.get_spec()
if in_name != "input_2":  # keep the stock feature name the app feeds
    ct.utils.rename_feature(spec, in_name, "input_2")
    ml = ct.models.MLModel(spec, weights_dir=ml.weights_dir)
outs = [o.name for o in ml.get_spec().description.output]
assert [i.name for i in ml.get_spec().description.input] == ["input_2"]
assert outs == ["Identity", "Identity_1", "Identity_2"], outs
ml.short_description = "Basic Pitch NMP (earsheet export). note=Identity_1 onset=Identity_2 contour=Identity"
ml.save(sys.argv[2])
print("coreml outputs", outs)
PY
[ -d "$OUT/tmp/BasicPitchPoly.mlpackage" ] || { echo "Core ML conversion failed" >&2; exit 1; }
(cd "$OUT/tmp" && zip -qrX "$OUT/$P-coreml.zip" BasicPitchPoly.mlpackage)

# Checksums + lock snippet + notes
(cd "$OUT" && sha256sum *.zip > SHA256SUMS)
PKG_TREE=$(cd "$OUT/tmp/BasicPitchPoly.mlpackage" && find . -type f -print0 | LC_ALL=C sort -z |
  while IFS= read -r -d '' f; do printf '%s' "${f#./}"; cat -- "$f"; done | sha256sum | awk '{print $1}')
COREML_ZIP_SHA=$(sha256sum "$OUT/$P-coreml.zip" | awk '{print $1}')
REPO=$(cd "$ROOT" && gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo yishengjiang99/earsheet)
cat > "$OUT/models.lock.snippet" <<EOT
# BasicPitchPoly.mlpackage from release $TAG (replace the three stock BasicPitchPoly.mlpackage/* lines)
$COREML_ZIP_SHA  BasicPitchPoly.mlpackage  https://github.com/$REPO/releases/download/$TAG/$P-coreml.zip
# package tree sha256 (what scripts/fetch-models and the app's compiled-model cache key hash): $PKG_TREE
EOT
TFJS_BIN_SHA=$(sha256sum "$OUT/tmp/tfjs/group1-shard1of1.bin" | awk '{print $1}')
TFJS_JSON_SHA=$(sha256sum "$OUT/tmp/tfjs/model.json" | awk '{print $1}')
{
  echo "Basic Pitch model export \`$TAG\` (generated by tools/model-export/export-model.sh)."
  echo
  echo "I/O: input \`input_2\` [1, 43844, 1] float32 at 22050 Hz mono; outputs \`Identity\` contour [1,172,264], \`Identity_1\` note [1,172,88], \`Identity_2\` onset [1,172,88]."
  echo
  echo "Integration: docs/finetune/IOS_MODEL_HANDOFF.md. Experiments: docs/finetune/EXPERIMENTS.md."
  echo
  echo '```'; cat "$OUT/SHA256SUMS"; echo "tfjs model.json $TFJS_JSON_SHA"; echo "tfjs group1-shard1of1.bin $TFJS_BIN_SHA"; echo "coreml package tree $PKG_TREE"; echo '```'
  echo
  echo "models.lock line:"; echo '```'; grep -v '^#' "$OUT/models.lock.snippet"; echo '```'
  if [ -n "$METRICS" ] && [ -f "$METRICS" ]; then
    echo; echo "Metrics (onset F1, mir_eval 50 ms):"; echo '```json'
    python3 -c "import json,sys; m=json.load(open(sys.argv[1])); print(json.dumps({k:m[k] for k in m if k in ('stamp','thresholds','synthetic_val','tests','best_epoch','train_minutes','decision','recommended_thresholds','note')}, indent=1))" "$METRICS"
    echo '```'
  fi
} > "$OUT/NOTES.md"
rm -rf "$OUT/tmp"
ls -la "$OUT"

if [ "$PUBLISH" = 1 ]; then
  cd "$ROOT"
  for t in "$TAG" $( [ "$LATEST" = 1 ] && echo model-latest ); do
    title="Model $TAG"; [ "$t" = model-latest ] && title="Model latest (= $TAG)"
    if gh release view "$t" >/dev/null 2>&1; then
      gh release upload "$t" "$OUT"/*.zip "$OUT/SHA256SUMS" "$OUT/models.lock.snippet" --clobber
      gh release edit "$t" --title "$title" --notes-file "$OUT/NOTES.md"
    else
      gh release create "$t" "$OUT"/*.zip "$OUT/SHA256SUMS" "$OUT/models.lock.snippet" \
        --title "$title" --notes-file "$OUT/NOTES.md" --target main --prerelease
    fi
  done
fi
