-- AI Music Radar API schema (MySQL 8 / MariaDB 10.6+). Applied in order by src/db.ts; recorded in schema_migrations.

CREATE TABLE IF NOT EXISTS devices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  install_id CHAR(36) NOT NULL,                -- per-install UUID generated by the app (Keychain)
  app_account_token CHAR(36) NULL,             -- UUID passed to StoreKit purchase(options: .appAccountToken)
  platform VARCHAR(16) NOT NULL DEFAULT 'ios',
  os_version VARCHAR(32) NULL,
  app_version VARCHAR(32) NULL,
  build_number VARCHAR(16) NULL,
  device_model VARCHAR(64) NULL,
  locale VARCHAR(35) NULL,
  timezone VARCHAR(64) NULL,
  first_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_devices_install (install_id),
  KEY idx_devices_token (app_account_token),
  KEY idx_devices_last_seen (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS push_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  device_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(200) NOT NULL,                 -- APNs device token (hex)
  environment ENUM('sandbox','production') NOT NULL,
  topic VARCHAR(128) NOT NULL DEFAULT 'com.ragnus.pnge',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  last_error VARCHAR(255) NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  last_sent_at TIMESTAMP(3) NULL,
  UNIQUE KEY uq_push_token (token),
  KEY idx_push_device (device_id),
  KEY idx_push_enabled_env (enabled, environment),
  CONSTRAINT fk_push_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Every verified StoreKit transaction (from /iap/verify, /iap/restore or ASSN v2).
CREATE TABLE IF NOT EXISTS iap_transactions (
  transaction_id VARCHAR(32) NOT NULL PRIMARY KEY,
  original_transaction_id VARCHAR(32) NOT NULL,
  product_id VARCHAR(128) NOT NULL,
  product_type VARCHAR(40) NULL,               -- Auto-Renewable Subscription / Non-Consumable
  app_account_token CHAR(36) NULL,
  environment ENUM('Sandbox','Production','Xcode','LocalTesting') NOT NULL,
  purchase_date TIMESTAMP(3) NULL,
  expires_date TIMESTAMP(3) NULL,
  offer_type TINYINT NULL,                     -- 1 intro, 2 promotional, 3 offer code, 4 win-back
  offer_discount_type VARCHAR(24) NULL,        -- FREE_TRIAL / PAY_AS_YOU_GO / PAY_UP_FRONT
  price_milli BIGINT NULL,                     -- price in milli-units of currency (Apple format)
  currency CHAR(3) NULL,
  storefront CHAR(3) NULL,
  revocation_date TIMESTAMP(3) NULL,
  revocation_reason TINYINT NULL,
  ownership_type VARCHAR(24) NULL,
  source VARCHAR(16) NOT NULL,                 -- verify / restore / notification
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_tx_original (original_transaction_id),
  KEY idx_tx_token (app_account_token),
  KEY idx_tx_purchase (purchase_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Current state per original_transaction_id (one row per subscription or lifetime purchase).
CREATE TABLE IF NOT EXISTS subscriptions (
  original_transaction_id VARCHAR(32) NOT NULL PRIMARY KEY,
  product_id VARCHAR(128) NOT NULL,
  kind ENUM('subscription','lifetime') NOT NULL,
  app_account_token CHAR(36) NULL,
  environment ENUM('Sandbox','Production','Xcode','LocalTesting') NOT NULL,
  status ENUM('active','trial','grace','billing_retry','expired','revoked') NOT NULL,
  expires_at TIMESTAMP(3) NULL,
  auto_renew TINYINT(1) NULL,
  auto_renew_product_id VARCHAR(128) NULL,
  is_trial TINYINT(1) NOT NULL DEFAULT 0,
  is_intro TINYINT(1) NOT NULL DEFAULT 0,
  revoked_at TIMESTAMP(3) NULL,
  last_transaction_id VARCHAR(32) NULL,
  last_event VARCHAR(48) NULL,
  first_purchase_at TIMESTAMP(3) NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY idx_sub_token (app_account_token),
  KEY idx_sub_status (status),
  KEY idx_sub_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- App Store Server Notifications V2 log (verified payloads, plus rejected attempts with error).
CREATE TABLE IF NOT EXISTS notification_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  notification_uuid CHAR(36) NULL,
  notification_type VARCHAR(48) NULL,
  subtype VARCHAR(48) NULL,
  environment VARCHAR(16) NULL,
  original_transaction_id VARCHAR(32) NULL,
  transaction_id VARCHAR(32) NULL,
  product_id VARCHAR(128) NULL,
  signed_date TIMESTAMP(3) NULL,
  verified TINYINT(1) NOT NULL,
  error VARCHAR(255) NULL,
  received_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_notification_uuid (notification_uuid),
  KEY idx_ne_received (received_at),
  KEY idx_ne_original (original_transaction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product analytics events (no audio, no PII).
CREATE TABLE IF NOT EXISTS telemetry_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  occurred_at TIMESTAMP(3) NOT NULL,
  received_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  install_id CHAR(36) NOT NULL,
  session_id CHAR(36) NULL,
  app_version VARCHAR(32) NULL,
  properties JSON NULL,
  KEY idx_te_name_time (name, occurred_at),
  KEY idx_te_time (occurred_at),
  KEY idx_te_device_time (install_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS push_sends (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  push_token_id BIGINT UNSIGNED NULL,
  environment VARCHAR(16) NOT NULL,
  title VARCHAR(120) NULL,
  status INT NULL,
  apns_id VARCHAR(64) NULL,
  reason VARCHAR(80) NULL,
  sent_by VARCHAR(32) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY idx_ps_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
